console.log(typeof 34);
console.log(typeof "34");
console.log(typeof "hello");
console.log(typeof true);
console.log(typeof null);
console.log(typeof undefined);
console.log(typeof [1,2,3]);
console.log(typeof {key:"value"});
console.log(typeof function(){});